# .woodpecker.yml
steps:
  - name: build-push
    image: docker
    when:
      - branch: master
      - event: push
    commands:
      - docker build . -t git.keannu1.duckdns.org/keannu125/drf_template
      - echo "$REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" --password-stdin -u "$REGISTRY_USERNAME"
      - docker push git.keannu1.duckdns.org/keannu125/drf_template
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets: [REGISTRY_USERNAME, REGISTRY_PASSWORD]
  - name: update deployment and reset database
    image: docker
    when:
      - branch: master
      - event: push
    commands:
      - mkdir -p /root/.ssh/
      - echo "$SSH_KEY" | tr -d '\r' > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > /root/.ssh/config
      - ssh root@10.0.10.4 '
        cd $PROJECT_DIR;
        docker-compose down;
        docker image rm git.keannu1.duckdns.org/keannu125/drf_template;
        docker volume rm git.keannu1.duckdns.org/keannu125/drf_template_db_data;
        docker compose up -d'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets: [SSH_KEY, PROJECT_DIR]
