labels:
  platform: linux/arm64

steps:
  - name: build
    image: docker
    environment:
      FORGEJO_REGISTRY_URL:
        from_secret: FORGEJO_REGISTRY_URL
      FORGEJO_REGISTRY_USERNAME:
        from_secret: FORGEJO_REGISTRY_USERNAME
      FORGEJO_REGISTRY_PASSWORD:
        from_secret: FORGEJO_REGISTRY_PASSWORD
      REGISTRY_IMAGE_TAG:
        from_secret: REGISTRY_IMAGE_TAG
    commands:
      - docker build -t "$REGISTRY_IMAGE_TAG" .
      - echo "$FORGEJO_REGISTRY_PASSWORD" | docker login "$FORGEJO_REGISTRY_URL" --password-stdin -u "$FORGEJO_REGISTRY_USERNAME"
      - docker push "$REGISTRY_IMAGE_TAG"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  - name: ntfy
    image: codeberg.org/l-x/woodpecker-ntfy
    settings:
      url:
        from_secret: NTFY_URL
      title: "${CI_REPO_NAME} build ${build.status}"
      priority: urgent
      click: https://api.template.06222001.xyz
      icon: https://github.com/woodpecker-ci/woodpecker/blob/main/docs/static/img/logo.svg
      tags: robot,${CI_REPO_NAME}
      message: ${CI_COMMIT_MESSAGE}
    depends_on: build
  - name: discord
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      message: "${CI_REPO_NAME} build ${build.status}"
    depends_on: build

when:
  - branch: master
    event: push
