labels:
  platform: linux/amd64

steps:
  - name: build
    image: docker
    environment:
      FORGEJO_REGISTRY_URL:
        from_secret: FORGEJO_REGISTRY_URL
      FORGEJO_REGISTRY_USERNAME:
        from_secret: FORGEJO_REGISTRY_USERNAME
      FORGEJO_REGISTRY_PASSWORD:
        from_secret: FORGEJO_REGISTRY_PASSWORD
      REGISTRY_IMAGE_TAG: git.06222001.xyz/keannu125/drf_template
    commands:
      - echo "$FORGEJO_REGISTRY_PASSWORD" | docker login "$FORGEJO_REGISTRY_URL" --password-stdin -u "$FORGEJO_REGISTRY_USERNAME"
      # Check if the image already exists
      - if docker manifest inspect "$REGISTRY_IMAGE_TAG:$CI_COMMIT_SHA" > /dev/null 2>&1; then
          echo "Image $REGISTRY_IMAGE_TAG:$CI_COMMIT_SHA already exists – skipping build."
          exit 0
        fi
      - docker buildx build -t "$REGISTRY_IMAGE_TAG:$CI_COMMIT_SHA" --platform linux/amd64,linux/arm64 .
      - docker push "$REGISTRY_IMAGE_TAG"
      - docker image rm "$REGISTRY_IMAGE_TAG"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
when:
  - branch: master
    event:
      - push
      - manual