labels:
  platform: linux/amd64

steps:
  - name: lint
    image: astral/uv:python3.13-trixie-slim
    commands:
      - uv sync --frozen --cache-dir /.cache/uv --link-mode=copy
      - export PATH=".venv/bin:$PATH"
      - ruff check src/. --no-fix --diff
      - isort --check --diff src/.
    volumes:
      - /tmp/.uv:/.cache/uv # Optimization: Shared UV cache on local build server
  - name: discord
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      message: >
        {{#success build.status}}
          ✅ [{{repo.name}}] Successful lint for build #{{build.number}}
          Branch: {{CI_COMMIT_BRANCH}}
          Commit: {{trimCommit CI_COMMIT_SHA 7}}
          By: {{CI_COMMIT_AUTHOR}}
        {{else}}
          ❌ [{{repo.name}}] Failed lint for build #{{build.number}}
          Branch: {{CI_COMMIT_BRANCH}}
          Commit: {{trimCommit CI_COMMIT_SHA 7}}
          By: {{CI_COMMIT_AUTHOR}}
        {{/success}}
    when:
      status: [ success, failure ]
      
when:
  - branch: master
    event:
      - push
      - manual
      - pull_request
