steps:
  - name: run post-deployment tests
    image: ghcr.io/usebruno/cli:3.5.1-alpine
    environment:
      BACKEND_DEBUG_USER_USERNAME: 
        from_secret: BACKEND_DEBUG_USER_USERNAME
      BACKEND_DEBUG_USER_PASSWORD:
        from_secret: BACKEND_DEBUG_USER_PASSWORD
    commands:
      - cd .bruno
      - bru run --env dev
      
when:
  - branch: master
    event:
      - push
      - manual

depends_on:
  - deploy