steps:
  - name: run post-deployment tests
    image: node:23-alpine
    environment:
      BACKEND_ADMIN_EMAIL: 
        from_secret: DEV_EMAIL
      BACKEND_PASSWORD:
        from_secret: DEV_PASSWORD
      BACKEND_URL: https://api.template.06222001.xyz/api/v1
    commands:
      - npm install -g @usebruno/cli --cache /tmp/.npm --prefer-offline
      - cd .bruno
      - bru run --env drf_template
    volumes:
      - /tmp/.npm:/tmp/.npm
      
when:
  - branch: master
    event:
      - push
      - manual

depends_on:
  - deploy