steps:
  - name: run pre-deployment tests
    image: node:23-alpine
    environment:
      BACKEND_ADMIN_EMAIL: 
        from_secret: DEV_EMAIL
      BACKEND_PASSWORD:
        from_secret: DEV_PASSWORD
    commands:
      - npm install -g @usebruno/cli --cache /tmp/.npm --prefer-offline
      - cd .bruno
      - bru run --env docker
    volumes:
      - /tmp/.npm:/tmp/.npm
      
when:
  - branch: master
    event:
      - push
      - manual

depends_on:
  - deploy

services:
  api:
    image: git.06222001.xyz/keannu125/goapi:latest
    environment:
      BACKEND_ADMIN_EMAIL: 
        from_secret: DEV_EMAIL
      BACKEND_PASSWORD:
        from_secret: DEV_PASSWORD

