steps:
  - name: run pre-deployment tests
    image: ghcr.io/usebruno/cli:3.5.1-alpine
    environment:
      BACKEND_ADMIN_EMAIL: 
        from_secret: DEV_EMAIL
      BACKEND_PASSWORD:
        from_secret: DEV_PASSWORD
    commands:
      - curl --retry 30 --retry-connrefused --retry-delay 2 --fail http://api:8000/api/v1/swagger
      - cd .bruno
      - bru run --env docker

when:
  - branch: master
    event:
      - push
      - manual

depends_on:
  - unit_tests

services:
  api:
    image: git.06222001.xyz/keannu125/drf_template:${CI_COMMIT_SHA}
    environment:
      BACKEND_ADMIN_EMAIL: 
        from_secret: DEV_EMAIL
      BACKEND_PASSWORD:
        from_secret: DEV_PASSWORD
      DJANGO_SETTINGS_MODULE: tests.settings
      BACKEND_GENERATE_CONFIG: true
      RUN_TYPE: api

