steps:
  - name: run unit tests
    image: astral/uv:python3.13-trixie-slim
    environment:
      BACKEND_GENERATE_TEST_CONFIG: True
    commands:
      - uv sync --frozen --cache-dir /.cache/uv --link-mode=copy
      - export PATH=".venv/bin:$PATH"
      - pytest --cov
    volumes:
      - /tmp/.uv:/.cache/uv
      
when:
  - branch: master
    event:
      - push
      - manual
      - pull_request